name: Call a reusable workflow

on:
  pull_request:

jobs:
  call-workflow-build-clang-doxy:
    uses: ./github/workflows/build-clang-doxy.yml@v1
  call-workflow-release-assets:
    uses: ./github/workflows/release-reusable.yml@v1