name: WipperSnapper Release CI

on: push

jobs:
  release-project:
    name: Release WipperSnapper
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-files
      - name: List Files
        run: ls
      - name: Upload Assets to the GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Wippersnapper_demo/build/*/*.uf2

  build-project:
    name: Build WipperSnapper
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arduino-platform: ["esp8266", "esp32", "funhouse",
                           "pyportal_tinyusb", "metro_m4_airliftlite_tinyusb"]
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
         repository: brentru/ci-arduino
         path: ci
    - name: Install CI-Arduino
      run: bash ci/actions_install.sh
      # manually install Adafruit WiFiNINA library fork
    - name: Install extra Arduino libraries
      run: |
        git clone --quiet https://github.com/adafruit/WiFiNINA.git /home/runner/Arduino/libraries/WiFiNINA
    - name: build platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}
    - name: Rename build artifacts to reflect the platform name
      run: |
            mv examples/*/build/*/Wippersnapper_demo.ino.uf2 examples/*/build/*/Wippersnapper.${{ matrix.arduino-platform }}.uf2
            mv examples/*/build/*/Wippersnapper_demo.ino.hex examples/*/build/*/Wippersnapper.${{ matrix.arduino-platform }}.hex
    - name: upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-files
        path: |
            examples/*/build/*/*.hex
            examples/*/build/*/*.uf2
