name: GitHub Actions for Wippersnapper Release Build System

on: [push]

#on:
#  release:
#    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arduino-platform: ["esp8266", "esp32", "funhouse",
                           "pyportal_tinyusb", "metro_m4_airliftlite_tinyusb"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
         repository: brentru/ci-arduino
         path: ci
         ref: build-support

    - name: pre-install
      run: bash ci/actions_install.sh

    # manually install Adafruit WiFiNINA library fork
    - name: extra libraries
      run: |
        git clone --quiet https://github.com/adafruit/WiFiNINA.git /home/runner/Arduino/libraries/WiFiNINA

    - name: Compile for all platforms and export build binaries
      run: python3 ci/build_platform.py --export-binary ${{ matrix.arduino-platform }}

    # clone Microsoft UF2
    - name: clone uf2 tools
      run: |
        git clone https://github.com/microsoft/uf2.git
        export UF2CONV=uf2/utils/uf2conv.py

    # check uf2 build dir.
    - name: check uf2 build dir
      run: |
        echo "ls /home/runner/work/Adafruit_Wippersnapper_Arduino/Adafruit_Wippersnapper_Arduino/examples/build"

