name: WipperSnapper Release CI

on:
  push
#  release:
#    types: [published]

jobs:
  release-project:
    name: Release WipperSnapper
    runs-on: ubuntu-latest
    needs: build-samd
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-files
      - name: List Files
        run: ls
      - name: Upload Assets to the GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
                  wippersnapper.*.*.uf2
                  wippersnapper.*.*.bin

  build-esp32:
    name: Build WipperSnapper ESP32
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arduino-platform: ["esp32"]
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - name: Get WipperSnapper version
      run: |
        git describe --dirty --tags
        echo >>$GITHUB_ENV WS_VERSION=$(git describe --dirty --tags)
    - uses: actions/checkout@v2
      with:
         repository: brentru/ci-arduino
         path: ci
    - name: Install CI-Arduino
      run: bash ci/actions_install.sh
    - name: build ESP32 platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}
    - name: Rename build artifacts to reflect the platform name
      run: |
            mv examples/Wippersnapper_demo/build/esp32.esp32.*/Wippersnapper_demo.ino.bin wippersnapper.${{ matrix.arduino-platform }}.${{ env.WS_VERSION }}.bin
    - name: upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-files
        path: |
            wippersnapper.${{ matrix.arduino-platform }}.${{ env.WS_VERSION }}.bin

  build-samd:
    name: Build WipperSnapper SAMD
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arduino-platform: ["pyportal_tinyusb", "metro_m4_airliftlite_tinyusb"]
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - name: Get WipperSnapper version
      run: |
        git describe --dirty --tags
        echo >>$GITHUB_ENV WS_VERSION=$(git describe --dirty --tags)
    - uses: actions/checkout@v2
      with:
         repository: brentru/ci-arduino
         path: ci
    - name: Install CI-Arduino
      run: bash ci/actions_install.sh
      # manually install Adafruit WiFiNINA library fork
    - name: Install extra Arduino libraries
      run: |
        git clone --quiet https://github.com/adafruit/WiFiNINA.git /home/runner/Arduino/libraries/WiFiNINA
    - name: build platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}
    - name: Rename build artifacts to reflect the platform name
      run: |
            mv examples/*/build/*/Wippersnapper_demo.ino.uf2 wippersnapper.${{ matrix.arduino-platform }}.${{ env.WS_VERSION }}.uf2
            mv examples/*/build/*/Wippersnapper_demo.ino.hex wippersnapper.${{ matrix.arduino-platform }}.${{ env.WS_VERSION }}.hex
    - name: upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-files
        path: |
            wippersnapper.${{ matrix.arduino-platform }}.${{ env.WS_VERSION }}.uf2
            wippersnapper.${{ matrix.arduino-platform }}.${{ env.WS_VERSION }}.hex
