# SPDX-FileCopyrightText: Adafruit Industries, 2022
#
# SPDX-License-Identifier: MIT
name: WipperSnapper Release CI

on:
  workflow_call

jobs:
  release-wippersnapper:
    name: Release WipperSnapper
    runs-on: ubuntu-latest
    needs: clang_and_doxy
    steps:
      - name: Download build artifacts from build-platform steps
        uses: actions/download-artifact@v2
        with:
          name: build-files
      - name: List Files
        run: ls
      - name: Upload Assets to the GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
                  wippersnapper.*.uf2
                  wippersnapper.*.bin
                  wippersnapper.*.zip
