# SPDX-FileCopyrightText: Brent Rubell for Adafruit Industries, 2022
#
# SPDX-License-Identifier: MIT
name: WipperSnapper Release Workflow

on:
  release:
    types: [published]

jobs:
  call-workflow-build:
    uses: adafruit/Adafruit_Wippersnapper_Arduino/.github/workflows/build-clang-doxy.yml@main
    secrets:
      token: ${{ secrets.GH_REPO_TOKEN }}

  call-workflow-release:
    needs: call-workflow-build
    uses: adafruit/Adafruit_Wippersnapper_Arduino/.github/workflows/release-callee.yml@main
