# SPDX-FileCopyrightText: Brent Rubell for Adafruit Industries, 2022
#
# SPDX-License-Identifier: MIT
name: WipperSnapper Full Release Workflow

on:
  release:

jobs:
  call-workflow-build:
    uses: brentru/Adafruit_Wippersnapper_Arduino/.github/workflows/build-clang-doxy.yml@workflow-reusable-2
    secrets:
      token: ${{ secrets.TOKEN }}

  call-workflow-release:
    needs: call-workflow-build
    uses: brentru/Adafruit_Wippersnapper_Arduino/.github/workflows/release-reusable.yml@workflow-reusable-2